/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'calendar-main': RouteRecordInfo<'calendar-main', '/calendar/main', Record<never, never>, Record<never, never>>,
    'cowork-disponibilita': RouteRecordInfo<'cowork-disponibilita', '/cowork/disponibilita', Record<never, never>, Record<never, never>>,
    'cowork-lista': RouteRecordInfo<'cowork-lista', '/cowork/lista', Record<never, never>, Record<never, never>>,
    'cowork-nuova': RouteRecordInfo<'cowork-nuova', '/cowork/nuova', Record<never, never>, Record<never, never>>,
    'cowork-servizi': RouteRecordInfo<'cowork-servizi', '/cowork/servizi', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'project-main': RouteRecordInfo<'project-main', '/project/main', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'users-main': RouteRecordInfo<'users-main', '/users/main', Record<never, never>, Record<never, never>>,
    'welcome-main': RouteRecordInfo<'welcome-main', '/welcome', Record<never, never>, Record<never, never>>,
  }
}
